# export
export WORKON_HOME=~/.virtualenvs
export STUDIO_JDK=/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk
export ANDROID_HOME=~/sdk/android/sdk
export PATH="~/.virtualenvs/atticenv/bin:$PATH"
export PATH=$PATH:/usr/local/m-cli
export PATH=$HOME/sdk/dart/flutter/bin:$PATH
export PATH=$HOME/sdk/android/sdk/platform-tools:$PATH
export PATH="/usr/local/sbin:$PATH"
export PATH=$HOME/.cargo/bin:$PATH
